main: lc.mine.skywars.SkywarsPlugin
name: Skywars
version: 2.0

description: Optimized skywars 1.8

author: iChocoMilk
website: ichocomilk.site

depends: [LCCore, SlimeWorldManager, LCCombat]

commands:
  skywars:
    description: "Skywars command"
  top:
    description: "See skywars tops"