main: lc.mine.skywars.SkywarsPlugin
name: Skywars
version: 2.0

description: Optimized skywars 1.8

author: iChocoMilk
website: ichocomilk.site

depends: [LCCore, SlimeWorldManager, LCCombat]

commands:
  skywars:
    description: "Skywars command"
  hentai:
    description: "Yes"
  leave:
    description: "Leave from the game"
  fly:
    description: "Enable/Disable fly"
  help:
    aliases: ["ayuda"]
    description: "Command for get help"